GRID_WIDTH = 27
GRID_HEIGHT = 31

NUM_MCTS_ITERATIONS = 10
EPSILON = 1e-6
SIMULATION_DEPTH = 5

NORMAL_GHOST_DISTANCE_THRESHOLD = 5
SCARED_GHOST_DISTANCE_THRESHOLD = 10

NUM_CLUSTERS = 4
CLUSTER_STARTING_COORDINATES = [[7, 8], [7, 23], [20, 8], [20, 23]]

SUPER_PELLET_LOCATIONS = [
    (3, 1),
    (3, 26),
    (23, 1),
    (23, 26),
]
GHOST_MAX_FRIGHT_STEPS = 40
SP_AGG_GHOST_DISTANCE_THRESHOLD = GHOST_MAX_FRIGHT_STEPS * 2
SP_DETECTION_THRESHOLD = 32
